### ISSUE TITLE
Minor styling tweaks

### ISSUE THREAD

**Issue by im-amy-lew** [im-amy-lew/mf-final-project#15]
**Tasks:**
- [x] Resize nav and icon to take up less vertical space on mobile screens
- [x] On `contact.html`, change "Submit" button color from default Bootstrap color (blue when clicked) to match the hover color (gold)
- [x] Make favicon background transparent (or white)
- [x] Add three more Font Awesome icons somewhere to fulfill final project requirements
- [x] Link to an external page that I created
