### ISSUE TITLE
Create "About" page

### ISSUE THREAD

**Issue by im-amy-lew** [im-amy-lew/mf-final-project#5]
**Tasks**
- [x] Create `about.html`
- [x] Add content
- [x] Link page to home page
- [x] Add basic styling
